/*
Generated by NNCU ver 1.0b 2020.07.14 with options:
-f smartcar_ad_dense_drop_025_adSize_1_nobn.h5 -ds smartcar_ad -m 0 --input_sizeof 2 -l 14 --input_shift 12 -as 10 -as2 5 --selfinf
*/

#include <stdint.h>
#include <stdlib.h>
#define ACT_RELU           1
#define ACT_SOFTMAX        2
#define ACT_RELU6          6
#define ACT_RELU8          18
#define ACT_RELU4          19
#define QUANTIZE_WORD_LEN  14
// --------------------------------------------------------------------------------
// Block 0: InputLayer - input
#define INPUT0_AI                     12
#define INPUT0_IC                     1
#define INPUT0_ICALL                  1
#define INPUT0_ICOFS                  0
#define INPUT0_IX                     8
#define INPUT0_IY                     1
#define INPUT0_OC                     1
#define INPUT0_OCALL                  1
#define INPUT0_OCOFS                  0
#define INPUT0_OX                     8
#define INPUT0_OY                     1
#define INPUT0_zzdbg_5_fracBitsOut    12
// --------------------------------------------------------------------------------
// Block 0: Flatten - flatten_2
#define FLAT0_AI                      12
#define FLAT0_IC                      1
#define FLAT0_ICALL                   1
#define FLAT0_ICOFS                   0
#define FLAT0_IX                      8
#define FLAT0_IY                      1
#define FLAT0_OC                      1
#define FLAT0_OCALL                   1
#define FLAT0_OCOFS                   0
#define FLAT0_OX                      1
#define FLAT0_OY                      8
#define FLAT0_zzdbg_5_fracBitsOut     12
// --------------------------------------------------------------------------------
// Block 1: Dense - dense_8
#define FC1_AA                        4
#define FC1_AI                        12
#define FC1_IC                        1
#define FC1_ICALL                     1
#define FC1_ICOFS                     0
#define FC1_IX                        1
#define FC1_IY                        8
#define FC1_OC                        1
#define FC1_OCALL                     1
#define FC1_OCOFS                     0
#define FC1_OX                        1
#define FC1_OY                        64
#define FC1_SB                        10
#define FC1_SO                        9
#define FC1_zzdbg_2_SH_WT             7
#define FC1_zzdbg_3_productShf        19
#define FC1_zzdbg_4_SB_AMP            9
#define FC1_zzdbg_5_fracBitsOut       10
#define FC1_zzdbg_8_AuxAct            "LINEAR"
// --------------------------------------------------------------------------------
// Block 1: Activation - activation_7
#define ACT1_ACT                      ACT_RELU
#define ACT1_AI                       10
#define ACT1_IC                       1
#define ACT1_ICALL                    1
#define ACT1_ICOFS                    0
#define ACT1_IX                       1
#define ACT1_IY                       64
#define ACT1_OC                       1
#define ACT1_OCALL                    1
#define ACT1_OCOFS                    0
#define ACT1_OX                       1
#define ACT1_OY                       64
#define ACT1_zzdbg_5_fracBitsOut      10
// --------------------------------------------------------------------------------
// Block 2: Dense - dense_9
#define FC2_AA                        4
#define FC2_AI                        10
#define FC2_IC                        1
#define FC2_ICALL                     1
#define FC2_ICOFS                     0
#define FC2_IX                        1
#define FC2_IY                        64
#define FC2_OC                        1
#define FC2_OCALL                     1
#define FC2_OCOFS                     0
#define FC2_OX                        1
#define FC2_OY                        48
#define FC2_SB                        12
#define FC2_SO                        11
#define FC2_zzdbg_2_SH_WT             11
#define FC2_zzdbg_3_productShf        21
#define FC2_zzdbg_4_SB_AMP            9
#define FC2_zzdbg_5_fracBitsOut       10
#define FC2_zzdbg_8_AuxAct            "LINEAR"
// --------------------------------------------------------------------------------
// Block 2: Activation - activation_8
#define ACT2_ACT                      ACT_RELU
#define ACT2_AI                       10
#define ACT2_IC                       1
#define ACT2_ICALL                    1
#define ACT2_ICOFS                    0
#define ACT2_IX                       1
#define ACT2_IY                       48
#define ACT2_OC                       1
#define ACT2_OCALL                    1
#define ACT2_OCOFS                    0
#define ACT2_OX                       1
#define ACT2_OY                       48
#define ACT2_zzdbg_5_fracBitsOut      10
// --------------------------------------------------------------------------------
// Block 3: Dense - dense_10
#define FC3_AA                        4
#define FC3_AI                        10
#define FC3_IC                        1
#define FC3_ICALL                     1
#define FC3_ICOFS                     0
#define FC3_IX                        1
#define FC3_IY                        48
#define FC3_OC                        1
#define FC3_OCALL                     1
#define FC3_OCOFS                     0
#define FC3_OX                        1
#define FC3_OY                        36
#define FC3_SB                        11
#define FC3_SO                        11
#define FC3_zzdbg_2_SH_WT             11
#define FC3_zzdbg_3_productShf        21
#define FC3_zzdbg_4_SB_AMP            10
#define FC3_zzdbg_5_fracBitsOut       10
#define FC3_zzdbg_8_AuxAct            "LINEAR"
// --------------------------------------------------------------------------------
// Block 3: Activation - activation_9
#define ACT3_ACT                      ACT_RELU
#define ACT3_AI                       10
#define ACT3_IC                       1
#define ACT3_ICALL                    1
#define ACT3_ICOFS                    0
#define ACT3_IX                       1
#define ACT3_IY                       36
#define ACT3_OC                       1
#define ACT3_OCALL                    1
#define ACT3_OCOFS                    0
#define ACT3_OX                       1
#define ACT3_OY                       36
#define ACT3_zzdbg_5_fracBitsOut      10
// --------------------------------------------------------------------------------
// Block 4: Dense - dense_11
#define FC4_AA                        4
#define FC4_AI                        10
#define FC4_IC                        1
#define FC4_ICALL                     1
#define FC4_ICOFS                     0
#define FC4_IX                        1
#define FC4_IY                        36
#define FC4_OC                        1
#define FC4_OCALL                     1
#define FC4_OCOFS                     0
#define FC4_OX                        1
#define FC4_OY                        64
#define FC4_SB                        13
#define FC4_SO                        13
#define FC4_zzdbg_2_SH_WT             13
#define FC4_zzdbg_3_productShf        23
#define FC4_zzdbg_4_SB_AMP            10
#define FC4_zzdbg_5_fracBitsOut       10
#define FC4_zzdbg_8_AuxAct            "LINEAR"
// --------------------------------------------------------------------------------
// Block 4: Activation - activation_10
#define ACT4_ACT                      ACT_RELU
#define ACT4_AI                       10
#define ACT4_IC                       1
#define ACT4_ICALL                    1
#define ACT4_ICOFS                    0
#define ACT4_IX                       1
#define ACT4_IY                       64
#define ACT4_OC                       1
#define ACT4_OCALL                    1
#define ACT4_OCOFS                    0
#define ACT4_OX                       1
#define ACT4_OY                       64
#define ACT4_zzdbg_5_fracBitsOut      10
// --------------------------------------------------------------------------------
// Block 5: Dense - dense_12
#define FC5_AA                        4
#define FC5_AI                        10
#define FC5_IC                        1
#define FC5_ICALL                     1
#define FC5_ICOFS                     0
#define FC5_IX                        1
#define FC5_IY                        64
#define FC5_OC                        1
#define FC5_OCALL                     1
#define FC5_OCOFS                     0
#define FC5_OX                        1
#define FC5_OY                        32
#define FC5_SB                        11
#define FC5_SO                        11
#define FC5_zzdbg_2_SH_WT             11
#define FC5_zzdbg_3_productShf        21
#define FC5_zzdbg_4_SB_AMP            10
#define FC5_zzdbg_5_fracBitsOut       10
#define FC5_zzdbg_8_AuxAct            "LINEAR"
// --------------------------------------------------------------------------------
// Block 5: Activation - activation_11
#define ACT5_ACT                      ACT_RELU
#define ACT5_AI                       10
#define ACT5_IC                       1
#define ACT5_ICALL                    1
#define ACT5_ICOFS                    0
#define ACT5_IX                       1
#define ACT5_IY                       32
#define ACT5_OC                       1
#define ACT5_OCALL                    1
#define ACT5_OCOFS                    0
#define ACT5_OX                       1
#define ACT5_OY                       32
#define ACT5_zzdbg_5_fracBitsOut      10
// --------------------------------------------------------------------------------
// Block 6: Dense - dense_13
#define FC6_AA                        4
#define FC6_AI                        10
#define FC6_IC                        1
#define FC6_ICALL                     1
#define FC6_ICOFS                     0
#define FC6_IX                        1
#define FC6_IY                        32
#define FC6_OC                        1
#define FC6_OCALL                     1
#define FC6_OCOFS                     0
#define FC6_OX                        1
#define FC6_OY                        16
#define FC6_SB                        14
#define FC6_SO                        15
#define FC6_zzdbg_2_SH_WT             15
#define FC6_zzdbg_3_productShf        25
#define FC6_zzdbg_4_SB_AMP            11
#define FC6_zzdbg_5_fracBitsOut       10
#define FC6_zzdbg_8_AuxAct            "LINEAR"
// --------------------------------------------------------------------------------
// Block 6: Activation - activation_12
#define ACT6_ACT                      ACT_RELU
#define ACT6_AI                       10
#define ACT6_IC                       1
#define ACT6_ICALL                    1
#define ACT6_ICOFS                    0
#define ACT6_IX                       1
#define ACT6_IY                       16
#define ACT6_OC                       1
#define ACT6_OCALL                    1
#define ACT6_OCOFS                    0
#define ACT6_OX                       1
#define ACT6_OY                       16
#define ACT6_zzdbg_5_fracBitsOut      10
// --------------------------------------------------------------------------------
// Block 7: Activation - re_lu_2
#define ACT7_ACT                      ACT_RELU8
#define ACT7_AI                       10
#define ACT7_IC                       1
#define ACT7_ICALL                    1
#define ACT7_ICOFS                    0
#define ACT7_IX                       1
#define ACT7_IY                       16
#define ACT7_OC                       1
#define ACT7_OCALL                    1
#define ACT7_OCOFS                    0
#define ACT7_OX                       1
#define ACT7_OY                       16
#define ACT7_zzdbg_5_fracBitsOut      10
// --------------------------------------------------------------------------------
// Block 7: Dense - dense_14
#define FC7_AA                        4
#define FC7_AI                        10
#define FC7_IC                        1
#define FC7_ICALL                     1
#define FC7_ICOFS                     0
#define FC7_IX                        1
#define FC7_IY                        16
#define FC7_OC                        1
#define FC7_OCALL                     1
#define FC7_OCOFS                     0
#define FC7_OX                        1
#define FC7_OY                        1
#define FC7_SB                        5
#define FC7_SO                        13
#define FC7_zzdbg_2_SH_WT             13
#define FC7_zzdbg_3_productShf        23
#define FC7_zzdbg_4_SB_AMP            18
#define FC7_zzdbg_5_fracBitsOut       10
#define FC7_zzdbg_8_AuxAct            "LINEAR"
extern const int16_t cg_FC1weit[]; // 512 - Co, Di: (64, 8)
extern const int16_t cg_FC1bias[]; // 64
extern const int16_t cg_FC2weit[]; // 3072 - Co, Di: (48, 64)
extern const int16_t cg_FC2bias[]; // 48
extern const int16_t cg_FC3weit[]; // 1728 - Co, Di: (36, 48)
extern const int16_t cg_FC3bias[]; // 36
extern const int16_t cg_FC4weit[]; // 2304 - Co, Di: (64, 36)
extern const int16_t cg_FC4bias[]; // 64
extern const int16_t cg_FC5weit[]; // 2048 - Co, Di: (32, 64)
extern const int16_t cg_FC5bias[]; // 32
extern const int16_t cg_FC6weit[]; // 512 - Co, Di: (16, 32)
extern const int16_t cg_FC6bias[]; // 16
extern const int16_t cg_FC7weit[]; // 16 - Co, Di: (1, 16)
extern const int16_t cg_FC7bias[]; // 1

#include <stdint.h>
#include "arm_math.h"
#include "arm_nnfunctions.h"
#include "aia_cmsisnn_ext.h"
// #include <model.h>

#define NNCU_EXT_VAR

#if (defined(__ICCARM__))
    #define NN_BUF_IMG_SECTION0 @".nn.buf.img0"
#elif defined(_MSC_VER)
    #define NN_BUF_IMG_SECTION0
#else
    #define NN_BUF_IMG_SECTION0 __attribute__((section(".nn.buf.img0")))
#endif
NNCU_EXT_VAR int32_t img_buffer0[(128 + 3) / 4] NN_BUF_IMG_SECTION0;

#if (defined(__ICCARM__))
    #define NN_BUF_IMG_SECTION1 @".nn.buf.img1"
#elif defined(_MSC_VER)
    #define NN_BUF_IMG_SECTION1
#else
    #define NN_BUF_IMG_SECTION1 __attribute__((section(".nn.buf.img1")))
#endif
NNCU_EXT_VAR int32_t img_buffer1[(128 + 3) / 4] NN_BUF_IMG_SECTION1;

#if (defined(__ICCARM__))
    #define NN_BUF_COL_SECTION @".nn.buf.col"
#elif defined(_MSC_VER)
    #define NN_BUF_COL_SECTION
#else
    #define NN_BUF_COL_SECTION __attribute__((section(".nn.buf.col")))
#endif
NNCU_EXT_VAR int32_t col_buf[(128 + 3) / 4] NN_BUF_COL_SECTION; // [2, 64, 2]
NNCU_EXT_VAR int16_t out_buf[1];
// total static buffer size: 0.38 kB

// generated RunModel(), returns the output buffer of the last layer
void* RunModel(const void *in_buf)
{ 
    
    memcpy(img_buffer0, in_buf, 16);
    // Block 1: Dense - dense_8
    arm_fully_connected_q15((int16_t*)img_buffer0/*0*/, cg_FC1weit/*weit*/, FC1_IY/*8*/, FC1_OY/*64*/, FC1_SB/*10*/
        , FC1_SO/*9*/, cg_FC1bias/*bias*/, (int16_t*)img_buffer1/*1*/, (int16_t*)col_buf);

    // Block 1: Activation - activation_7
    arm_relu_q15((int16_t*)img_buffer1/*1*/, (uint32_t)(ACT1_IX * ACT1_IY * ACT1_IC)/*1x64x1*/);

    // Block 2: Dense - dense_9
    arm_fully_connected_q15((int16_t*)img_buffer1/*1*/, cg_FC2weit/*weit*/, FC2_IY/*64*/, FC2_OY/*48*/, FC2_SB/*12*/
        , FC2_SO/*11*/, cg_FC2bias/*bias*/, (int16_t*)img_buffer0/*0*/, (int16_t*)col_buf);

    // Block 2: Activation - activation_8
    arm_relu_q15((int16_t*)img_buffer0/*0*/, (uint32_t)(ACT2_IX * ACT2_IY * ACT2_IC)/*1x48x1*/);

    // Block 3: Dense - dense_10
    arm_fully_connected_q15((int16_t*)img_buffer0/*0*/, cg_FC3weit/*weit*/, FC3_IY/*48*/, FC3_OY/*36*/, FC3_SB/*11*/
        , FC3_SO/*11*/, cg_FC3bias/*bias*/, (int16_t*)img_buffer1/*1*/, (int16_t*)col_buf);

    // Block 3: Activation - activation_9
    arm_relu_q15((int16_t*)img_buffer1/*1*/, (uint32_t)(ACT3_IX * ACT3_IY * ACT3_IC)/*1x36x1*/);

    // Block 4: Dense - dense_11
    arm_fully_connected_q15((int16_t*)img_buffer1/*1*/, cg_FC4weit/*weit*/, FC4_IY/*36*/, FC4_OY/*64*/, FC4_SB/*13*/
        , FC4_SO/*13*/, cg_FC4bias/*bias*/, (int16_t*)img_buffer0/*0*/, (int16_t*)col_buf);

    // Block 4: Activation - activation_10
    arm_relu_q15((int16_t*)img_buffer0/*0*/, (uint32_t)(ACT4_IX * ACT4_IY * ACT4_IC)/*1x64x1*/);

    // Block 5: Dense - dense_12
    arm_fully_connected_q15((int16_t*)img_buffer0/*0*/, cg_FC5weit/*weit*/, FC5_IY/*64*/, FC5_OY/*32*/, FC5_SB/*11*/
        , FC5_SO/*11*/, cg_FC5bias/*bias*/, (int16_t*)img_buffer1/*1*/, (int16_t*)col_buf);

    // Block 5: Activation - activation_11
    arm_relu_q15((int16_t*)img_buffer1/*1*/, (uint32_t)(ACT5_IX * ACT5_IY * ACT5_IC)/*1x32x1*/);

    // Block 6: Dense - dense_13
    arm_fully_connected_q15((int16_t*)img_buffer1/*1*/, cg_FC6weit/*weit*/, FC6_IY/*32*/, FC6_OY/*16*/, FC6_SB/*14*/
        , FC6_SO/*15*/, cg_FC6bias/*bias*/, (int16_t*)img_buffer0/*0*/, (int16_t*)col_buf);

    // Block 6: Activation - activation_12
    arm_relu_q15((int16_t*)img_buffer0/*0*/, (uint32_t)(ACT6_IX * ACT6_IY * ACT6_IC)/*1x16x1*/);

    // Block 7: Activation - re_lu_2
    aia_relu8_q15((int16_t*)img_buffer0/*0*/, (uint32_t)(ACT7_IX * ACT7_IY * ACT7_IC)/*1x16x1*/, ACT7_AI);

    // Block 7: Dense - dense_14
    arm_fully_connected_q15((int16_t*)img_buffer0/*0*/, cg_FC7weit/*weit*/, FC7_IY/*16*/, FC7_OY/*1*/, FC7_SB/*5*/
        , FC7_SO/*13*/, cg_FC7bias/*bias*/, (int16_t*)img_buffer1/*1*/, (int16_t*)col_buf);

    memcpy(out_buf, img_buffer1, 2);

    return out_buf;
}

