/*
 * aia_cmsisnn_ext.h
 *
 *  Created on: 2021Äê7ÔÂ11ÈÕ
 *      Author: 936305695
 */

#ifndef APP_USR_NEURALNETWORK_UNUSED_AIA_CMSISNN_EXT_H_
#define APP_USR_NEURALNETWORK_UNUSED_AIA_CMSISNN_EXT_H_





#endif /* APP_USR_NEURALNETWORK_UNUSED_AIA_CMSISNN_EXT_H_ */
