################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
SRC_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
SECONDARY_SIZE := 
COMPILED_SRCS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
App/Sys \
App/Usr/NeuralNetwork \
App/Usr \
App \
Configurations/Debug \
Configurations \
. \
Driver/SysDriver \
Driver/UsrDriver/Camera \
Driver/UsrDriver/EEPROM \
Driver/UsrDriver/ICM20602 \
Driver/UsrDriver/LCD \
Driver/UsrDriver/SD \
Libraries/Infra/Platform/Tricore/Compilers \
Libraries/Infra/Ssw/TC37A/Tricore \
Libraries/Service/CpuGeneric/If \
Libraries/Service/CpuGeneric/StdIf \
Libraries/Service/CpuGeneric/SysSe/Bsp \
Libraries/Service/CpuGeneric/SysSe/Math \
Libraries/iLLD/TC37A/Tricore/Asclin/Asc \
Libraries/iLLD/TC37A/Tricore/Asclin/Spi \
Libraries/iLLD/TC37A/Tricore/Asclin/Std \
Libraries/iLLD/TC37A/Tricore/Ccu6/Icu \
Libraries/iLLD/TC37A/Tricore/Ccu6/PwmBc \
Libraries/iLLD/TC37A/Tricore/Ccu6/Std \
Libraries/iLLD/TC37A/Tricore/Ccu6/TPwm \
Libraries/iLLD/TC37A/Tricore/Ccu6/Timer \
Libraries/iLLD/TC37A/Tricore/Cpu/Irq \
Libraries/iLLD/TC37A/Tricore/Cpu/Std \
Libraries/iLLD/TC37A/Tricore/Cpu/Trap \
Libraries/iLLD/TC37A/Tricore/Dma/Dma \
Libraries/iLLD/TC37A/Tricore/Dma/Std \
Libraries/iLLD/TC37A/Tricore/Evadc/Adc \
Libraries/iLLD/TC37A/Tricore/Evadc/Std \
Libraries/iLLD/TC37A/Tricore/Flash/Std \
Libraries/iLLD/TC37A/Tricore/Gpt12/IncrEnc \
Libraries/iLLD/TC37A/Tricore/Gpt12/Std \
Libraries/iLLD/TC37A/Tricore/Gtm/Atom/Pwm \
Libraries/iLLD/TC37A/Tricore/Gtm/Std \
Libraries/iLLD/TC37A/Tricore/Gtm/Tim/In \
Libraries/iLLD/TC37A/Tricore/Gtm/Tom/Pwm \
Libraries/iLLD/TC37A/Tricore/Gtm/Tom/PwmHl \
Libraries/iLLD/TC37A/Tricore/Gtm/Tom/Timer \
Libraries/iLLD/TC37A/Tricore/Gtm/Trig \
Libraries/iLLD/TC37A/Tricore/I2c/I2c \
Libraries/iLLD/TC37A/Tricore/I2c/Std \
Libraries/iLLD/TC37A/Tricore/Mtu/Std \
Libraries/iLLD/TC37A/Tricore/Pms/Std \
Libraries/iLLD/TC37A/Tricore/Port/Io \
Libraries/iLLD/TC37A/Tricore/Port/Std \
Libraries/iLLD/TC37A/Tricore/Qspi/SpiMaster \
Libraries/iLLD/TC37A/Tricore/Qspi/SpiSlave \
Libraries/iLLD/TC37A/Tricore/Qspi/Std \
Libraries/iLLD/TC37A/Tricore/Scu/Std \
Libraries/iLLD/TC37A/Tricore/Src/Std \
Libraries/iLLD/TC37A/Tricore/Stm/Std \
Libraries/iLLD/TC37A/Tricore/_Impl \
Libraries/iLLD/TC37A/Tricore/_Lib/DataHandling \
Libraries/iLLD/TC37A/Tricore/_PinMap \
OS/Debug \
OS/Device/BEEP \
OS/Device/BLE \
OS/Device/Capture \
OS/Device/Communicate \
OS/Device/DSensor \
OS/Device/Demo \
OS/Device/ESensor \
OS/Device/IMU \
OS/Device/KEY \
OS/Device/LED \
OS/Device/Memory \
OS/Device/Motor \
OS/Device/Screen \
OS/Device/Servo \
OS/Device/Switch \
OS/Device/WirelessSerial \
OS/FatFs \
OS/FatFs/src \
OS/FatFs/src/option \
OS/Malloc \
OS/Task \
OS/Time \
OS/UI \
OS \

